language: python
python:
- 3.8
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
install:
- pip install pipenv
- pipenv install --dev --ignore-pipfile --deploy
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- source $HOME/miniconda/etc/profile.d/conda.sh
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- pytest --cov-report xml --cov-report term
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
before_deploy:
- chmod +x ./final_project/tasks/integration.sh
- bash ./final_project/tasks/integration.sh
- pipenv uninstall csci-utils
- pipenv update
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: csc29-covid-viz
  on:
    repo: lekshmisanthosh-chill/2021-sp-final-project-lekshmisanthosh-chill
    branch: main
  skip_cleanup: 'true'
