language: python
python:
- 3.8
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
install:
- pip install pipenv
- pipenv install --dev --ignore-pipfile --deploy
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- source $HOME/miniconda/etc/profile.d/conda.sh
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- pytest --cov-report xml --cov-report term
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
before_deploy:
- chmod +x ./final_project/tasks/integration.sh
- bash ./final_project/tasks/integration.sh
- pipenv uninstall csci-utils
- pipenv update
deploy:
  provider: heroku
  api_key:
    secure: jjH4A6VLs1bNG5D+KSOjxJYF1PQW9ZNfv2eb+mEKgcPCiO+nlqNyXg8YCwlVfxop38242NuuYDm38k/pdPflSPNG4WUm4BNieuphjcsMW703pUnPBC+P2qAg5GDB7SLuEL67KCnrC2dyE+moEapU94gGaz7Sn35GITDtJgqJyc35ZzXbIUGu7YVio1zrhuvjMHdqZJOpR82VyNcvRUSqBlWdgLUnmQguAOnBh3GJTjO6P9UbKMrQ4Ugv09nouD0HICwXZFyXklNglEKJXugjItf02ffv3wpSkdSwnDRPtPF5l8vARTVXUotNESPCsbEh1i3VMZO8fOHQZe825GF2RB4PEJzbuw2VAYvk4iGJmt0Gza8c2rwzQmESXc2aJm9FfyC4RZXSpdPKdXvJup9ftnJrq4DnNlywgyD8fIwwxhkpzjHZh1tn9GlohlbQLRckuFnR6QEf+Ok1IfsNlGrShH4fHrGHlEdfMNlr+T43bzuJt1+8znmt6Qjn+0GWUj3jLEFevrSs4VcxoksrSl48U6oK021R6eRnLm8Sr8D2Q0bOHVt652cOOvXXZo0NZgIcEVUq1TWWto5zkkIgXKERp1PGYC3uk3/DiHN48uP2CDsXc8HuNpKeTM+0fWrP6KLQiASWaCgzDy+tw932YYdv9b62VYmQzK8t+yHKkD1eUjI=
  app: cs29-covid-visualizer
  on:
    repo: lekshmisanthosh-chill/2021-sp-final-project-lekshmisanthosh-chill
    branch: main
  skip_cleanup: 'true'
